### PR TITLE
Add feedbacks on publish page

### LINKED ISSUE #53: Add feedbacks on publish page (marker)
As Designs, we have to add some feedback on current publish page, and create two publish pages that differs (the marker will show the final marker image to be downloaded, the location page will show the locations on the map).

Details at Design Figma file: https://www.figma.com/file/TUjZ2KYsmhA5LUkt9KIhcB/ARjs-Studio?node-id=0%3A1

image

image

### PR DESCRIPTION
**Pull request by mingir2**
closes #53 

Screen Shot 2020-05-21 at 1 28 19 PM
Screen Shot 2020-05-21 at 1 28 41 PM
Screen Shot 2020-05-21 at 1 29 12 PM

## Summary
- Major changes to the pages folder structure.
- Remove main.css dependencies from marker.html and location.html pages.
- Clean up style.css.

- Add feedback to the Publish page.
  - Added marker preview and download.
  - Added error message and success message.
  - Utilize sessionStorage for persistent data for uploaded contents.

### CODE REVIEW

**Comment by mingir2** [comment]
I need someone to implement the displayMap() function and we should be able to merge this PR.

**Comment by nicolocarpignoli** [comment]
I'd rather merge this one https://github.com/AR-js-org/studio/pull/56 and then your PR because folder refactoring. I can manage myself to align this PR after the other has been merged.

**Comment by nicolocarpignoli** [comment]
@mingir2 solved the conflict and aligned with master branch. When you have added the 'disclaimer' line on this, I will review

**Comment by nicolocarpignoli** [comment]
@mingir2 Anna added the disclaimer line, see: 

image

**Comment by nicolocarpignoli** [comment]
Avoid the email field for now, we will use it post MVP

**Comment by mingir2** [comment]
@nicolocarpignoli I updated the publish page with the disclaimer and cleaned up the stylesheets. I noticed that the previous merge didn't include the setDefaultMarker function in marker.js, so publish doesn't work without uploading a marker image.

**Comment by nicolocarpignoli** [comment]
@mingir2 whoops, my fault. Can you please re-added it back?

**Comment by mingir2** [comment]
@nicolocarpignoli all good!

**Comment by nicolocarpignoli** [comment]
As on 16th of June we will present AR.js Studio, it will be great to have the full working flow for marker based.
I suggest to make this PR only for marker, and open a new issue for the location publish (so with location folder refactoring + map embed on publish page).

**Comment by nicolocarpignoli** [comment]
if you agree @mingir2 I can manage issues and review this PR for marker based only

**Comment by mingir2** [comment]
@nicolocarpignoli That makes sense. Is the GitHub integration part of the flow?

**Comment by nicolocarpignoli** [comment]
Yes. @le0m what are we missing for the Github integration on the frontend side? Do we have anything?

**Comment by nicolocarpignoli** [comment]
@mingir2 we can see the Github integration on a separate issue. Anyway, I have found errors on this.
I can't see the marker no final stage and I have an alert error when accessing the publish page from marker page.

**Comment by nicolocarpignoli** [comment]
Found the problem. I'm fixing...

**Comment by nicolocarpignoli** [comment]
We have a problem with the quota - strange but uploading an image i get quota exceeded, the same does not happen for a heavier video... We have to fix this.

**Comment by nicolocarpignoli** [comment]
Have a 'trick' idea, will try now.

**Comment by nicolocarpignoli** [comment]
So, we can't use 
- URL with encodeURIComponent
- Session storage
- Local Storage

I will just create a page that is a popup so we already have all the data.

**Comment by nicolocarpignoli** [comment]
I have used window.name to pass the whole JSON stringified. Seems strange to me that it works, but seems to be fine. Please review and test it.

**Comment by mingir2** [comment]
@nicolocarpignoli Using window.name should be okay. It's more or less the same with sessionStorage.

**Comment by nicolocarpignoli** [comment]
@mingir2 if you have tested and works okay, I will merge. Let me know

**Pull request merged**
