### PR TITLE
Adjusted page element sizes

### PR DESCRIPTION
**Pull request by fcor**
As discussed with @nicolocarpignoli, I've just resized some elements according to viewport. Please give it a try on your machines and let me know how does it look.

### CODE REVIEW

**Comment by kalwalt** [comment]
@fcor I will test it!

**Comment by kalwalt** [comment]
On my Ubuntu desktop machine, home page:

Studio 2020-03-30 18-35-44

Marker based:

Studio 2020-03-30 18-38-05

Location Based:

Studio 2020-03-30 18-37-07

Does it is ok? Looks in the same way on your machine?

**Comment by fcor** [comment]
@kalwalt Looks good!

What do you think? Any suggestions on margins, spacing and sizing in general?

**Comment by kalwalt** [comment]
Looks good also to me! I have any suggestions at the moment. Looks good also for a tablet device Ipad) under emulation.

**Comment by nicolocarpignoli** [comment]
fixed some minor issues (curso pointer on a label, removed fixed width form text-input). Look way more better with your work @fcor 

Thank you!

**Pull request merged**
