### PR TITLE
Issue45-Enable_Marker_Footer

### PR DESCRIPTION
**Pull request by gciandro13**
Hi nic,
I did not find the way to edit the "shadowRoot" problem. 
I will work on it next days, if it is not a problem.

### CODE REVIEW

**Comment by mingir2** [comment]
@nicolocarpignoli Is it not possible to use id attribute for the buttons? "zip-button" and "publish-button" don't have any style attached to it and they are only used for event handling and such.
@gciandro13 I think you meant to name the function enablePageFooter rather than enableMarkerFooter

**Comment by nicolocarpignoli** [comment]
Seems correct both suggestions - please @gciandro13 modify and then I will merge

**Comment by gciandro13** [comment]
Ok; I fixed with @mingir2 suggestions

**Comment by nicolocarpignoli** [comment]
Thank you all, merging!

**Pull request merged**
