### PR TITLE
Feature/leafletmap

### PR DESCRIPTION
**Pull request by ba5eem**
I have tried to match the figma as close as possible. The Set location button is disabled until a location has been clicked and/or use my location has been used. That is a quick change, just didn'nt know what the next screen is - so for now it calls a window alert. The map and styles are included. the map could be used again by changing the path and re-using the class.

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
I only pushed some cosmetic stuff about code. 
Anyway: It does not work manually entering coordinates: we should update the map and set location on blur on one of the two coordinates input, if the coordinates are valid. Now it works only setting the marker on the map

**Comment by ba5eem** [comment]
I noticed you removed the marker when map clicked / use my location is used, is that what you mean by blur? ill work on the text box

**Comment by nicolocarpignoli** [comment]
> I noticed you removed the marker when map clicked / use my location is used, no need for marker?
> ill work on the 'manual option'

sorry wrong commit, have re-added it back

**Comment by ba5eem** [comment]
Can i close this pull request and submit another one with the gps coords text input feature updated?

**Comment by nicolocarpignoli** [comment]
@ba5eem yes, absolutely no problem. We can merge this one and you can start from this. You should be able to merge it by yourself, feel free to do as you wish.

**Pull request closed without merging**
