### PR TITLE
Landing

### PR DESCRIPTION
**Pull request by mingir2**
**What kind of change does this PR introduce?**
Creates the landing page and associated js and css files.

**Can it be referenced to an Issue? If so what is the issue # ?**
No.

**How can we test it?**
User testing.

**Summary**
Added components folder
- modules, custom js and css files

Added pages folder
- html files

Added index.html
- landing page

Added style.css
- default stylesheet with the components from the Figma wire

Added script.js

**Does this PR introduce a breaking change?**
No.

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
@mingir2  
It's pretty much all ok, It's missing a bit of margin between elements (vertical margin) and the font-size of the 'start building' button is not enough big

image

**Comment by nicolocarpignoli** [comment]
Also, I would rename all the CSS classes with lowercase  https://css-tricks.com/forums/topic/css-naming-conventions/

**Comment by nicolocarpignoli** [comment]
Also, I would do a semantic but important modify:

From design, we have two radio button that 'will decide' the next location the user will go, and a button. Semantically speaking, the 'Start Building' is not a Button but should be an anchor (that looks like a button, of course, to follow design).

So I will change the button element 
```
<input
            class="PrimaryButton"
            type="submit"
            value="Start building"
            onclick="startBuildingOnclick()"
          />
```

with 

```
<a href="" >Start Building</a>
```

and, on event handler for radio buttons, we will directly change the 'href' attribute of it, with new location.

This is also important for accessibility.

**Comment by kalwalt** [comment]
There is any logo in the page, does it is missed or it will be added later? Because I can see only the alt message...

**Comment by nicolocarpignoli** [comment]
> There is any logo in the page, does it is missed or it will be added later? Because I can see only the alt message...

It's a placeholder, the logo will be handled on a separate issue :)

**Comment by kalwalt** [comment]
Ok i get it. :slightly_smiling_face: 
Two things: On desktop the page (div with background class) don't take the full page? It's happens only to me? it is shifted to the left.
It would be nice also that the cursor changes over the button to enhance user interaction.
On mobile looks very cool, but for some ratios the title `Web-enabled AR experiences` tends to exit the screen.

**Comment by fcor** [comment]
> Ok i get it. 🙂
> Two things: On desktop the page (div with background class) don't take the full page? It's happens only to me? it is shifted to the left.
> It would be nice also that the cursor changes over the button to enhance user interaction.
> On mobile looks very cool, but for some ratios the title `Web-enabled AR experiences` tends to exit the screen.

I think the button hover state and specific styles could be added later, we are just using Glitch's default one. If no one has started with that, I can work on buttons after this PR is merged 😃

**Comment by kalwalt** [comment]
@mingir2 @fcor @nicolocarpignoli Can't wait to see working this! :smile:

**Comment by mingir2** [comment]
@nicolocarpignoli I renamed the CSS classes and add margin for the button. Also, I modified the radiobutton onclick function, so that it directly changes href of the start button like you said.

@kalwalt we don't have any design for mobile yet, I don't know if we'll have any. But I did change the title font size for that, and it does poke at really small screen width.

Thank you all for waiting! I really appreciate the feedback.

**Pull request merged**
