### PR TITLE
Create page-header component and use absolute path

### PR DESCRIPTION
**Pull request by mingir2**
- Added page-header custom web component and updated all three pages (index, marker, location) accordingly.
- Fixed all relative path to absolute path. This has an implication that local testing/development will require a use of local server.

To test that the routing is working properly, feel free to check out the Glitch link. It should be up to date with this PR.
- https://arjs-studio.glitch.me/

### CODE REVIEW

**Comment by mingir2** [comment]
On a side note, the page-header component is in the script.js because I felt like creating a separate .js file would introduce unnecessary complexity. But, I'm open to suggestions.

**Comment by fcor** [comment]
Looks good! I like the approach of removing styles from styles.css and placing it in components. 

Talked to @nicolocarpignoli yesterday and I think I'm going to create some more components (Buttons, Upload file, dropdown select), otherwise we will end up with some duplicate code. For example, we want to share the upload file section between both marker and location based. Since that section includes buttons, if we place the button inside the component, and there are more buttons accross the page (outside this component), styles will be duplicated and would be hard to maintain/update in the future.

If we are moving on that direction, it would be better to create separate files for each component, right?

**Comment by kalwalt** [comment]
@mingir2 very interesting!, i would like to look at the glitch link but seems i can not access to it. :cry:

**Comment by mingir2** [comment]
I made a change to the way I described what I did. I think it should make more sense now.

@fcor Only downside of doing that is having multiple lines of <script> tags for each components, but I'm okay with having separate files as well and it's as easy as doing couple copy and paste anyway.

@kawalt I wish I knew how to help! Glitch should be open to everyone to view by default. Can you describe the problem more in detail?

**Comment by kalwalt** [comment]
@mingir2 `ERR_CONNECTION_REFUSED impossible to reach the website` and i have a good internet connection. Maybe the link is wrong?

**Comment by mingir2** [comment]
@kalwalt try this http://arjs-studio.glitch.me/

**Comment by nicolocarpignoli** [comment]
Glitch always gives error to me too. Don't know why (it's not something related to your glitch)

**Comment by nicolocarpignoli** [comment]
@kalwalt you'd better clone the repo locally and test the branch directly. I would do that myself too.

**Comment by kalwalt** [comment]
@nicolocarpignoli @mingir2 seems that the only way to see the changes is pulling from the branch, glitch is not working. By the way, looks good the page! :slightly_smiling_face:

**Comment by nicolocarpignoli** [comment]
Yes, I agree with what @fcor said and I have moved the component on a separate folder and files, hope you don't mind :)

We will have a lot of files, and it's good to have separate files and import, on each html, only the web components we need. 

Anyway, We can merge if it's good also for you guys. Great work!

**Comment by nicolocarpignoli** [comment]
I merge this so @fcor can add the header on its Location Based page PR. Thank you!

**Pull request merged**
