### PR TITLE
Default marker page + refactor on marker page

### PR DESCRIPTION
**Pull request by nicolocarpignoli**
Closes https://github.com/AR-js-org/studio/issues/54

### CODE REVIEW

**Comment by mingir2** [comment]
@nicolocarpignoli 

There's few things that needs to be fixed.
1. Using the default marker will prompt the user to upload when they click download package.
2. Uploading and removing an image won't display the default marker image.
3. Uploaded content also has "Download marker" option.

**Comment by nicolocarpignoli** [comment]
@mingir2 

Point 1 and 3 are bugs, I will fix. Point 2 is an enhancement that I think we can avoid for the MVP.

**Comment by nicolocarpignoli** [comment]
@mingir2 Pushed. can you please check again? I hope I have not left out some bugfix. Thanks

**Comment by mingir2** [comment]
@nicolocarpignoli Looks good. Thank you for making those bug fixes. My last commit doesn't have any functional changes. I just moved the inline script function to marker.js and simplified the template function just a little bit.

I want to revisit the templates once our MVP is done. it already feels a bit hacky and out of context right now, so it might become a pain to deal with later on.

**Comment by nicolocarpignoli** [comment]
yes, totally agree. As soon as we publish MVP, we can write down 2-3 issues to refactor things technically speaking (under the hood) to make them more maintainable. We will have them  as we will not push other features very soon after MVP release, but rather concentrate on publish this.

**Comment by nicolocarpignoli** [comment]
Okay, I will merge so you can align your PR to master @mingir2

**Pull request merged**
